#version: '3.8'

services:
  # ==========================================
  # CAPA BASE DE DATOS (MySQL)
  # ==========================================
  banco-db:
    build: 
      context: ./mi-banco-mysql1  # <--- NOTA ESTE CAMBIO: Busca en la carpeta de al lado
      dockerfile: Dockerfile
    container_name: mysql-db-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: banco_db
      MYSQL_USER: banco_user
      MYSQL_PASSWORD: banco_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - banco_network

  # ==========================================
  # CAPA APLICACIÓN (Node.js)
  # ==========================================
  banco-app:
    build:
      context: ./mi-banco-app1 # <--- NOTA ESTE CAMBIO: Busca en la carpeta de al lado
      dockerfile: Dockerfile
    container_name: node-app-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=banco-db  # Nombre del servicio de arriba
      - DB_PORT=3306
      - DB_USER=banco_user
      - DB_PASSWORD=banco_pass
      - DB_NAME=banco_db
    depends_on:
      - banco-db
    networks:
      - banco_network

# ==========================================
# DEFINICIÓN DE VOLÚMENES Y REDES
# ==========================================
volumes:
  mysql_data:
    name: banco_mysql_volume

networks:
  banco_network:
    name: banco_custom_network
    driver: bridge
